---
settings:
  name: NetApp Solutions SAP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: SAP 솔루션
    url: "/index.html"
  - section: bp
  - section: backup
  - section: lifecycle
  - section: briefs
  - title: FlexPod SAP 솔루션
    url: https://docs.netapp.com/us-en/flexpod/ent-db/index.html
  - title: NetApp 솔루션
    url: https://docs.netapp.com/us-en/netapp-solutions/
  - title: 법적 고지
    url: "/reference_legal_notices.html"
homepage:
  tiles:
  - title: 구성 모범 사례
    links:
    - title: 비디오 데모
      url: sap-bp-videos.html
    - title: 블로그
      url: sap-bp-blogs.html
    - title: 도구
      url: sap-bp-tools.html
  - title: 백업, 복원 및 재해 복구
    links:
    - title: 비디오 데모
      url: sap-dr-videos.html
    - title: 블로그
      url: sap-dr-blogs.html
    - title: 도구
      url: sap-dr-tools.html
  - title: 라이프사이클 관리
    links:
    - title: 비디오 데모
      url: sap-lcm-videos.html
    - title: 블로그
      url: sap-lcm-blogs.html
    - title: 도구
      url: sap-lcm-tools.html
  - title: 모든 SAP 솔루션
    links:
    - title: 새로운 기능
      url: sap-whatsnew.html
    - title: 비디오 데모
      url: sap-videos.html
    - title: 블로그
      url: sap-blogs.html
