---
sidebar: sidebar 
permalink: backup/saphana-br-scs-where-to-find-additional-information.html 
keywords:  
summary:  
---
= 추가 정보 및 버전 기록을 찾을 수 있는 위치
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:saphana-br-scs-advanced-configuration-and-tuning.html["이전: 고급 구성 및 조정."]

이 문서에 설명된 정보에 대해 자세히 알아보려면 다음 문서 및/또는 웹 사이트를 검토하십시오.

* SnapCenter 리소스 페이지 를 참조하십시오
+
https://www.netapp.com/us/documentation/snapcenter-software.aspx["https://www.netapp.com/us/documentation/snapcenter-software.aspx"^]

* SnapCenter 소프트웨어 설명서
+
https://docs.netapp.com/us-en/snapcenter/index.html["https://docs.netapp.com/us-en/snapcenter/index.html"^]

* TR-4667: SnapCenter를 사용하여 SAP 시스템 복사 자동화
+
https://www.netapp.com/pdf.html?item=/media/17111-tr4667pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17111-tr4667pdf.pdf"^]

* TR-4719: SnapCenter를 통한 SAP HANA 시스템 복제, 백업 및 복구
+
https://www.netapp.com/pdf.html?item=/media/17030-tr4719pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17030-tr4719pdf.pdf"^]

* TR-4018: NetApp ONTAP 시스템을 SAP 환경 관리와 통합
+
https://www.netapp.com/pdf.html?item=/media/17195-tr4018pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17195-tr4018pdf.pdf"^]

* TR-4646: 스토리지 복제를 사용한 SAP HANA 재해 복구
+
https://www.netapp.com/pdf.html?item=/media/8584-tr4646pdf.pdf["https://www.netapp.com/pdf.html?item=/media/8584-tr4646pdf.pdf"^]





=== 버전 기록

|===
| 버전 | 날짜 | 문서 버전 기록 


| 버전 1.0 | 2017년 7월  a| 
* 최초 릴리스.




| 버전 1.1 | 2017년 9월  a| 
* “고급 구성 및 조정” 섹션이 추가되었습니다.
* 사소한 수정.




| 버전 2.0 | 2018년 3월  a| 
* SnapCenter 4.0에 대한 업데이트: 새로운 데이터 볼륨 리소스로 단일 파일 SnapRestore 작업이 개선되었습니다




| 버전 3.0 | 2020년 1월  a| 
* “SnapCenter 개념 및 모범 사례” 섹션이 추가되었습니다.
* SnapCenter 4.3을 다루는 업데이트: 자동 검색 자동 복구 HANA MDC 다중 테넌트 단일 테넌트 복원 작업 지원




| 버전 3.1 | 2020년 7월  a| 
* 사소한 업데이트 및 수정: SnapCenter 4.3.1 IBM Power 기반 Linux용 SSL 통신 중앙 플러그인 배포의 구성을 통한 NFSv4 지원




| 버전 3.2 | 2020년 11월  a| 
* HANA 2.0 SPS5에 필요한 데이터베이스 사용자 권한이 추가되었습니다.




| 버전 3.3 | 2021년 5월  a| 
* SSL hdbsql 구성 섹션을 업데이트했습니다.
* Linux LVM 지원이 추가되었습니다.




| 버전 3.4 | 2021년 8월  a| 
* 자동 검색 구성 비활성화 설명이 추가되었습니다.




| 버전 3.5 | 2022년 2월  a| 
* SnapCenter 4.6에 대한 업데이트 및 HANA 시스템 복제 지원 HANA 시스템에 대한 자동 검색 지원 기능이 포함되어 있습니다.


|===