---
sidebar: sidebar 
permalink: backup/saphana-backup-anf-overview.html 
keywords: overview, introduction, tr-4905, 4905, tr4905, snapcenter service, anf, azure netapp files 
summary: 이 기술 보고서에서는 NetApp SnapCenter 서비스 및 Azure NetApp Files를 통해 SAP HANA 데이터 보호에 대한 모범 사례를 다룹니다. 또한 백업, 복원 및 복구 작업을 비롯한 SnapCenter 서비스의 개념, 구성 권장사항, 운영 워크플로우를 다룹니다. 
---
= TR-4905: SnapCenter 기반 SAP HANA 백업 및 복구(Azure NetApp Files 서비스 포함)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


NetApp, Nils Bauer

이 기술 보고서에서는 NetApp SnapCenter 서비스 및 Azure NetApp Files를 통해 SAP HANA 데이터 보호에 대한 모범 사례를 다룹니다. 또한 백업, 복원 및 복구 작업을 비롯한 SnapCenter 서비스의 개념, 구성 권장사항, 운영 워크플로우를 다룹니다.

오늘날 기업은 SAP 애플리케이션을 위해 중단 없는 지속적인 가용성을 필요로 합니다. 지속적으로 증가하는 데이터 볼륨이 요구되고 시스템 백업과 같은 일상적인 유지 관리 작업이 필요할 때 일관된 성능 수준을 기대합니다. SAP 데이터베이스 백업은 중요한 작업이며 운영 SAP 시스템에 상당한 성능 영향을 미칠 수 있습니다.

백업 윈도우는 줄어들고 있으며, 백업할 데이터의 양은 계속 증가하고 있습니다. 따라서 비즈니스 프로세스에 미치는 영향을 최소화하면서 백업을 수행할 수 있는 시간을 찾기가 어렵습니다. SAP 운영 및 비운영 시스템의 다운타임을 최소화하여 데이터 손실과 비즈니스 비용을 절감해야 하기 때문에 SAP 시스템을 복원 및 복구하는 데 걸리는 시간이 문제가 됩니다.

다음은 SAP 백업 및 복구와 관련된 당면 과제를 요약한 것입니다.

* * 운영 SAP 시스템에 대한 성능 영향 * 일반적으로 기존 복제 기반 백업은 데이터베이스 서버, 스토리지 시스템 및 스토리지 네트워크에 과부하가 발생하기 때문에 운영 SAP 시스템에서 상당한 성능 저하를 일으킬 수 있습니다.
* * 백업 기간 단축 * SAP 시스템에서 진행 중인 대화 또는 배치 작업이 거의 없을 때만 기존 백업을 수행할 수 있습니다. SAP 시스템이 24시간 사용 중일 때는 백업 스케줄링이 더 어려워집니다.
* * 빠른 데이터 증가. * 빠른 데이터 증가 및 백업 시간 단축을 위해서는 백업 인프라에 대한 지속적인 투자가 필요합니다. 다시 말해, 추가 백업 디스크 공간과 더 빠른 백업 네트워크를 확보해야 합니다. 또한 이러한 백업 자산의 저장 및 관리에 드는 지속적인 비용도 모두 다루어야 합니다. 증분 또는 차등 백업에서는 이러한 문제를 해결할 수 있지만 이 방식을 사용하면 매우 느리고 번거로우며 복잡한 복원 프로세스가 확인하기가 더 어렵습니다. 이러한 시스템은 일반적으로 비즈니스에 허용되지 않는 방식으로 RTO(복구 시간 목표) 및 RPO(복구 시점 목표) 시간을 늘립니다.
* * 가동 중단 시간의 비용 증가. * SAP 시스템의 계획되지 않은 가동 중지 시간은 일반적으로 비즈니스 재무에 영향을 줍니다. 계획되지 않은 다운타임의 상당 부분은 SAP 시스템을 복원 및 복구하는 데 필요한 요구 사항에 의해 사용됩니다. 따라서 원하는 RTO는 백업 및 복구 아키텍처의 설계를 결정합니다.
* * SAP 업그레이드 프로젝트를 위한 백업 및 복구 시간 * SAP 업그레이드를 위한 프로젝트 계획에는 SAP 데이터베이스의 백업이 3개 이상 포함됩니다. 이러한 백업은 업그레이드 프로세스에 사용할 수 있는 시간을 크게 줄여줍니다. 진행 결정은 일반적으로 이전에 생성된 백업에서 데이터베이스를 복원 및 복구하는 데 필요한 시간을 기준으로 합니다. 시스템을 이전 상태로 복원하는 것이 아니라 신속한 복원을 통해 업그레이드 중에 발생할 수 있는 문제를 해결하는 데 더 많은 시간을 할애할 수 있습니다.


link:saphana-backup-anf-the-netapp-solution.html["다음은 NetApp 솔루션입니다."]
