---
sidebar: sidebar 
permalink: backup/saphana-backup-anf-snapcenter-service-snapshot-backup-configuration-overview.html 
keywords:  
summary:  
---
= SnapCenter 서비스 스냅샷 백업 구성 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:saphana-backup-anf-snapcenter-service-policy-configuration.html["이전: SnapCenter 서비스 정책 구성"]

SnapCenter 서비스는 다음과 같은 두 가지 스냅샷 백업 작업 유형을 지원합니다.

* Snapshot 작업을 사용하여 SAP HANA 데이터 백업
+
데이터베이스 정합성 보장 및 백업 카탈로그 관리를 위한 HANA SQL 문을 Azure NetApp Files 스냅샷 작업과 결합하는 SAP HANA 데이터베이스 데이터 볼륨 백업

* Snapshot 백업 작업을 사용하여 비정형 데이터가 포함된 볼륨 백업
+
HANA 데이터베이스와 통신할 필요가 없는 바이너리, 구성 파일 등의 백업 Azure NetApp Files 스냅샷 백업 작업을 통해 백업이 실행됩니다. SnapCenter 서비스에서는 두 가지 하위 유형을 사용하여 해당 볼륨이 특정 HANA 시스템에 속하는지 또는 여러 HANA 시스템에서 사용되는 글로벌 공유 볼륨인지 여부를 정의합니다.

+
** SAP HANA 데이터베이스의 비데이터 볼륨 백업
+
HANA 공유 볼륨 등 특정 HANA 시스템과 관련된 볼륨의 백업입니다.

** 글로벌 비 데이터 볼륨 백업
+
SAP 전송 디렉토리와 같은 특정 HANA 시스템과 관련되지 않은 볼륨의 백업입니다.

+
다음 섹션에서는 세 가지 다른 백업 유형의 구성에 대해 설명합니다.





link:saphana-backup-anf-backup-configuration-of-sap-hana-database-backups.html["다음: SAP HANA 데이터베이스 백업의 백업 구성"]
