---
sidebar: sidebar 
permalink: bp/hana-aff-fc-host-setup_single.html 
keywords: multipathing, fcp, hba, configure 
summary: 호스트를 설정하기 전에 NetApp Support 사이트에서 NetApp SAN 호스트 유틸리티를 다운로드하고 HANA 서버에 설치해야 합니다. 호스트 유틸리티 설명서에는 사용된 FCP HBA에 따라 설치해야 하는 추가 소프트웨어에 대한 정보가 포함되어 있습니다. 
---
= 단일 호스트 설정
:allow-uri-read: 




== 단일 호스트 설정

[role="lead"]
이 장에서는 LINUX LVM을 사용하여 SAP HANA 단일 호스트를 설정하는 방법을 설명합니다.



== SAP HANA 단일 호스트 시스템에 대한 LUN 구성

SAP HANA 호스트에서 다음 표에 나와 있는 것처럼 볼륨 그룹 및 논리적 볼륨을 생성하고 마운트해야 합니다.

|===
| 논리적 볼륨/LUN | SAP HANA 호스트의 마운트 지점 | 참고 


| LV: FC5_data_mnt0000-vol | /하나/데이터/FC51/mnt00001 | /etc/fstab 항목을 사용하여 마운트되었습니다 


| LV: FC5_log_mnt00001-vol | /HANA/log/FC5/mnt00001 | /etc/fstab 항목을 사용하여 마운트되었습니다 


| LUN: FC5_shared | /HANA/공유/FC5 | /etc/fstab 항목을 사용하여 마운트되었습니다 
|===

NOTE: 설명된 구성을 사용하면 `/usr/sap/FC5` 사용자 FC5adm의 기본 홈 디렉토리가 저장된 디렉토리는 로컬 디스크에 있습니다.  디스크 기반 복제를 사용하는 재해 복구 설정에서 NetApp 추가 LUN을 생성하는 것을 권장합니다. `FC5_shared` 볼륨에 대한 `/usr/sap/FC5` 모든 파일 시스템이 중앙 저장소에 있도록 디렉토리를 만듭니다.



=== LVM 볼륨 그룹 및 논리 볼륨을 생성합니다

. 모든 LUN을 물리적 볼륨으로 초기화합니다.
+
....
pvcreate /dev/mapper/hana-FC5_data_mnt00001
pvcreate /dev/mapper/hana-FC5_data2_mnt00001
pvcreate /dev/mapper/hana-FC5_log_mnt00001
pvcreate /dev/mapper/hana-FC5_log2_mnt00001
....
. 각 데이터 및 로그 파티션에 대한 볼륨 그룹을 생성합니다.
+
....
vgcreate FC5_data_mnt00001 /dev/mapper/hana-FC5_data_mnt00001 /dev/mapper/hana-FC5_data2_mnt00001
vgcreate FC5_log_mnt00001 /dev/mapper/hana-FC5_log_mnt00001 /dev/mapper/hana-FC5_log2_mnt00001
....
. 각 데이터 및 로그 파티션에 대한 논리적 볼륨을 생성합니다. 볼륨 그룹당 사용되는 LUN 수(이 예에서는 2개)와 데이터의 경우 스트라이프 크기 256K, 로그의 경우 64k를 사용하는 스트라이프 크기를 사용합니다. SAP는 볼륨 그룹당 하나의 논리적 볼륨만 지원합니다.
+
....
lvcreate --extents 100%FREE -i 2 -I 256k --name vol FC5_data_mnt00001
lvcreate --extents 100%FREE -i 2 -I 64k --name vol FC5_log_mnt00001
....
. 다른 모든 호스트에서 물리적 볼륨, 볼륨 그룹 및 볼륨 그룹을 검사합니다.


....
modprobe dm_mod
pvscan
vgscan
lvscan
....

NOTE: 이러한 명령을 실행해도 볼륨이 없으면 다시 시작해야 합니다.

논리적 볼륨을 마운트하려면 논리적 볼륨을 활성화해야 합니다. 볼륨을 활성화하려면 다음 명령을 실행합니다.

....
vgchange -a y
....


=== 파일 시스템을 생성합니다

모든 데이터 및 로그 논리 볼륨과 HANA 공유 LUN에 XFS 파일 시스템을 만듭니다.

....
mkfs.xfs /dev/mapper/FC5_data_mnt00001-vol
mkfs.xfs /dev/mapper/FC5_log_mnt00001-vol
mkfs.xfs /dev/mapper/svm1-FC5_shared
....


=== 마운트 지점을 생성합니다

필요한 마운트 지점 디렉토리를 만들고 데이터베이스 호스트에 대한 권한을 설정합니다.

....
sapcc-hana-tst:/ # mkdir -p /hana/data/FC5/mnt00001
sapcc-hana-tst:/ # mkdir -p /hana/log/FC5/mnt00001
sapcc-hana-tst:/ # mkdir -p /hana/shared
sapcc-hana-tst:/ # chmod -R 777 /hana/log/FC5
sapcc-hana-tst:/ # chmod -R 777 /hana/data/FC5
sapcc-hana-tst:/ # chmod 777 /hana/shared
....


=== 파일 시스템을 마운트합니다

시스템 부팅 중에 파일 시스템을 마운트하려면 다음을 사용하십시오.  `/etc/fstab` 구성 파일에 필요한 파일 시스템을 추가합니다.  `/etc/fstab` 구성 파일:

....
# cat /etc/fstab
/dev/mapper/svm1-FC5_shared /hana/shared xfs defaults 0 0
/dev/mapper/FC5_log_mnt00001-vol /hana/log/FC5/mnt00001 xfs relatime,inode64 0 0
/dev/mapper/FC5_data_mnt00001-vol /hana/data/FC5/mnt00001 xfs relatime,inode64 0 0
....

NOTE: 데이터 및 로그 LUN을 위한 XFS 파일 시스템은 'laytime' 및 'inode64' 마운트 옵션으로 마운트되어야 합니다.

파일 시스템을 마운트하려면 다음을 실행하세요. `mount -a` 호스트에서 명령을 내립니다.
