---
sidebar: sidebar 
permalink: bp/hana-aff-fc-host-setup_multi.html 
keywords: multipathing, fcp, hba, configure 
summary: 호스트를 설정하기 전에 NetApp Support 사이트에서 NetApp SAN 호스트 유틸리티를 다운로드하고 HANA 서버에 설치해야 합니다. 호스트 유틸리티 설명서에는 사용된 FCP HBA에 따라 설치해야 하는 추가 소프트웨어에 대한 정보가 포함되어 있습니다. 
---
= 여러 호스트 설정
:allow-uri-read: 




== 여러 호스트 설정

[role="lead"]
이 장에서는 2+1 SAP HANA 다중 호스트 시스템 설정을 예로 들어 설명합니다.



== SAP HANA 다중 호스트 시스템을 위한 LUN 구성

SAP HANA 호스트에서 다음 표에 나와 있는 것처럼 볼륨 그룹 및 논리적 볼륨을 생성하고 마운트해야 합니다.

|===
| 논리 볼륨(LV) 또는 볼륨입니다 | SAP HANA 호스트의 마운트 지점 | 참고 


| LV: FC5_data_mnt00001-vol | /HANA/data/FC5/mnt00001 | 보관 커넥터를 사용하여 장착합니다 


| LV: FC5_log_mnt00001-vol | /HANA/log/FC5/mnt00001 | 보관 커넥터를 사용하여 장착합니다 


| LV: FC5_data_mnt00002-vol | /HANA/data/FC5/mnt00002 | 보관 커넥터를 사용하여 장착합니다 


| LV: FC5_log_mnt00002-vol | /HANA/log/FC5/mnt00002 | 보관 커넥터를 사용하여 장착합니다 


| 볼륨: FC5_shared | /HANA/공유 | NFS 및 /etc/fstab 항목을 사용하여 모든 호스트에 마운트됩니다 
|===

NOTE: 설명된 구성을 사용하면 `/usr/sap/FC5` 사용자 FC5adm의 기본 홈 디렉토리가 저장되는 디렉토리는 각 HANA 호스트의 로컬 디스크에 있습니다.  디스크 기반 복제를 사용하는 재해 복구 설정에서 NetApp 4개의 추가 하위 디렉토리를 만드는 것을 권장합니다. `FC5_shared` 볼륨에 대한 `/usr/sap/FC5` 각 데이터베이스 호스트가 모든 파일 시스템을 중앙 저장소에 두도록 파일 시스템을 구성합니다.



=== LVM 볼륨 그룹 및 논리 볼륨을 생성합니다

. 모든 LUN을 물리적 볼륨으로 초기화합니다.
+
....
pvcreate /dev/mapper/hana-FC5_data_mnt00001
pvcreate /dev/mapper/hana-FC5_data2_mnt00001
pvcreate /dev/mapper/hana-FC5_data_mnt00002
pvcreate /dev/mapper/hana-FC5_data2_mnt00002
pvcreate /dev/mapper/hana-FC5_log_mnt00001
pvcreate /dev/mapper/hana-FC5_log2_mnt00001
pvcreate /dev/mapper/hana-FC5_log_mnt00002
pvcreate /dev/mapper/hana-FC5_log2_mnt00002
....
. 각 데이터 및 로그 파티션에 대한 볼륨 그룹을 생성합니다.
+
....
vgcreate FC5_data_mnt00001 /dev/mapper/hana-FC5_data_mnt00001 /dev/mapper/hana-FC5_data2_mnt00001
vgcreate FC5_data_mnt00002 /dev/mapper/hana-FC5_data_mnt00002 /dev/mapper/hana-FC5_data2_mnt00002
vgcreate FC5_log_mnt00001 /dev/mapper/hana-FC5_log_mnt00001 /dev/mapper/hana-FC5_log2_mnt00001
vgcreate FC5_log_mnt00002 /dev/mapper/hana-FC5_log_mnt00002 /dev/mapper/hana-FC5_log2_mnt00002
....
. 각 데이터 및 로그 파티션에 대한 논리적 볼륨을 생성합니다. 볼륨 그룹당 사용되는 LUN 수(이 예에서는 2개)와 데이터의 경우 스트라이프 크기 256K, 로그의 경우 64k를 사용하는 스트라이프 크기를 사용합니다. SAP는 볼륨 그룹당 하나의 논리적 볼륨만 지원합니다.
+
....
lvcreate --extents 100%FREE -i 2 -I 256k --name vol FC5_data_mnt00001
lvcreate --extents 100%FREE -i 2 -I 256k --name vol FC5_data_mnt00002
lvcreate --extents 100%FREE -i 2 -I 64k --name vol FC5_log_mnt00002
lvcreate --extents 100%FREE -i 2 -I 64k --name vol FC5_log_mnt00001
....
. 다른 모든 호스트에서 물리적 볼륨, 볼륨 그룹 및 볼륨 그룹을 검사합니다.


....
modprobe dm_mod
pvscan
vgscan
lvscan
....

NOTE: 이러한 명령을 실행해도 볼륨이 없으면 다시 시작해야 합니다.

논리적 볼륨을 마운트하려면 논리적 볼륨을 활성화해야 합니다. 볼륨을 활성화하려면 다음 명령을 실행합니다.

....
vgchange -a y
....


=== 파일 시스템을 생성합니다

모든 데이터 및 로그 논리 볼륨에 XFS 파일 시스템을 만듭니다.

....
mkfs.xfs FC5_data_mnt00001-vol
mkfs.xfs FC5_data_mnt00002-vol
mkfs.xfs FC5_log_mnt00001-vol
mkfs.xfs FC5_log_mnt00002-vol
....


=== 마운트 지점을 생성합니다

필요한 마운트 지점 디렉토리를 만들고 모든 작업자 및 대기 호스트에 대한 권한을 설정합니다.

....
sapcc-hana-tst:/ # mkdir -p /hana/data/FC5/mnt00001
sapcc-hana-tst:/ # mkdir -p /hana/log/FC5/mnt00001
sapcc-hana-tst:/ # mkdir -p /hana/data/FC5/mnt00002
sapcc-hana-tst:/ # mkdir -p /hana/log/FC5/mnt00002
sapcc-hana-tst:/ # mkdir -p /hana/shared
sapcc-hana-tst:/ # chmod –R 777 /hana/log/FC5
sapcc-hana-tst:/ # chmod –R 777 /hana/data/FC5
sapcc-hana-tst:/ # chmod 777 /hana/shared
....


=== 파일 시스템을 마운트합니다

마운트하려면  `/hana/shared` 시스템 부팅 중 파일 시스템을 사용하여  `/etc/fstab` 구성 파일에 다음을 추가합니다.  `/hana/shared` 파일 시스템에  `/etc/fstab` 각 호스트의 구성 파일.

....
sapcc-hana-tst:/ # cat /etc/fstab
<storage-ip>:/hana_shared /hana/shared nfs rw,vers=3,hard,timeo=600, intr,noatime,nolock 0 0
....

NOTE: 모든 데이터 및 로그 파일 시스템은 SAP HANA 스토리지 커넥터를 통해 마운트됩니다.

파일 시스템을 마운트하려면 각 호스트에서 'mount –a' 명령을 실행합니다.
