---
sidebar: sidebar 
permalink: bp/saphana-fas-nfs_i_o_stack_configuration_for_sap_hana.html 
keywords: io, stack, configuration, sap, hana, fas, nfs 
summary: SAP HANA 1.0 SPS10부터 SAP는 입출력 동작을 조정하고 사용되는 파일 및 스토리지 시스템에 맞게 데이터베이스를 최적화하는 매개 변수를 도입했습니다. 
---
= SAP HANA용 I/O 스택 구성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:saphana-fas-nfs_sap_hana_installation_preparations_for_nfsv4.html["이전: NFSv4를 위한 SAP HANA 설치 준비"]

SAP는 SAP HANA 1.0 SPS10부터 I/O 동작을 조정하고 사용되는 파일 및 스토리지 시스템에 맞게 데이터베이스를 최적화하는 매개 변수를 도입했습니다.

NetApp은 이상적인 가치를 정의하기 위해 성능 테스트를 실시했습니다. 다음 표에는 성능 테스트에서 유추된 최적의 값이 나와 있습니다.

|===
| 매개 변수 | 값 


| max_parallel_io_requests | 128 


| Async_read_submit입니다 | 켜짐 


| Async_write_submit_active입니다 | 켜짐 


| Async_write_submit_blocks입니다 | 모두 
|===
SAP HANA 1.0 버전 최대 SPS12의 경우, SAP 참고 사항에 설명된 대로 SAP HANA 데이터베이스 설치 중에 이러한 매개 변수를 설정할 수 있습니다 https://launchpad.support.sap.com/["2267798: hdbparam을 사용하여 설치하는 동안 SAP HANA 데이터베이스 구성"^].

또는 "hdbparam" 프레임워크를 사용하여 SAP HANA 데이터베이스 설치 후 매개 변수를 설정할 수도 있습니다.

....
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00> hdbparam --paramset fileio.max_parallel_io_requests=128
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00> hdbparam --paramset fileio.async_write_submit_active=on
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00> hdbparam --paramset fileio.async_read_submit=on
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00> hdbparam --paramset fileio.async_write_submit_blocks=all
....
SAP HANA 2.0부터는 hdbparam이 더 이상 사용되지 않고 매개 변수가 global.ini` 으로 옮겨졌습니다. 매개 변수는 SQL 명령 또는 SAP HANA Studio를 사용하여 설정할 수 있습니다. 자세한 내용은 SAP 노트 를 참조하십시오 https://launchpad.support.sap.com/["2399079 : HANA 2에서 hdbparam 제거"^]. 다음 텍스트에서와 같이 global.ini 내에서 매개 변수를 설정할 수도 있습니다.

....
nf2adm@stlrx300s8-6: /usr/sap/NF2/SYS/global/hdb/custom/config> cat global.ini
…
[fileio]
async_read_submit = on
async_write_submit_active = on
max_parallel_io_requests = 128
async_write_submit_blocks = all
…
....
SAP HANA 2.0 SPS5를 사용하기 때문에 'etParameter.py' 스크립트를 사용하여 올바른 매개 변수를 설정할 수 있습니다.

....
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00/exe/python_support>
python setParameter.py -set=SYSTEM/global.ini/fileio/max_parallel_io_requests=128
python setParameter.py -set=SYSTEM/global.ini/fileio/async_read_submit=on
python setParameter.py -set=SYSTEM/global.ini/fileio/async_write_submit_active=on
python setParameter.py -set=SYSTEM/global.ini/fileio/async_write_submit_blocks=all
....
link:saphana-fas-nfs_sap_hana_data_volume_size.html["다음: SAP HANA 데이터 볼륨 크기"]
