---
sidebar: sidebar 
permalink: bp/saphana-fas-nfs_sap_hana_installation_preparations_for_nfsv4.html 
keywords: sap, hana, installation, preparations, nfsv4, user, authentication, storage, controller, hosts 
summary: 'NFS 버전 4 이상의 경우 사용자 인증이 필요합니다. LDAP(Lightweight Directory Access Protocol) 서버와 같은 중앙 사용자 관리 도구 또는 로컬 사용자 계정을 사용하여 이 인증을 수행할 수 있습니다.' 
---
= NFSv4를 위한 SAP HANA 설치 준비
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NFS 버전 4 이상의 경우 사용자 인증이 필요합니다. LDAP(Lightweight Directory Access Protocol) 서버와 같은 중앙 사용자 관리 도구 또는 로컬 사용자 계정을 사용하여 이 인증을 수행할 수 있습니다. 다음 섹션에서는 로컬 사용자 계정을 구성하는 방법에 대해 설명합니다.

 관리 사용자 `<sid>adm`,`<sid>crypt`SAP HANA 소프트웨어 설치를 시작하기 전에 SAP HANA 호스트 및 스토리지 컨트롤러에 및 `sapsys` 그룹을 수동으로 생성해야 합니다.



== SAP HANA 호스트

존재하지 않는 경우 SAP HANA 호스트에 'sapsys' 그룹을 생성해야 합니다. 스토리지 컨트롤러의 기존 그룹 ID와 충돌하지 않는 고유한 그룹 ID를 선택해야 합니다.

SAP HANA 호스트에서 사용자 `<sid>adm` 및 `<sid>crypt` 이 생성됩니다. 스토리지 컨트롤러의 기존 사용자 ID와 충돌하지 않는 고유한 ID를 선택해야 합니다.

다중 호스트 SAP HANA 시스템의 경우 모든 SAP HANA 호스트에서 사용자 및 그룹 ID가 동일해야 합니다. 그룹 및 사용자는 영향을 받는 라인을 `/etc/passwd` 소스 시스템에서 다른 모든 SAP HANA 호스트로 복사하여 다른 SAP HANA 호스트에 `/etc/group` 생성됩니다.


NOTE: NFSv4 도메인은 모든 Linux 서버("/etc/idmapd.conf") 및 SVM에서 동일한 값으로 설정해야 합니다. Linux 호스트에 대한 파일 '/etc/idmapd.conf'에서 도메인 매개 변수 "Domain=<domain-name>"을 설정합니다.

NFS IDMAPD 서비스를 활성화하고 시작합니다.

....
systemctl enable nfs-idmapd.service
systemctl start nfs-idmapd.service
....

NOTE: 최신 Linux 커널에는 이 단계가 필요하지 않습니다. 경고 메시지는 무시해도 됩니다.



== 스토리지 컨트롤러

사용자 ID 및 그룹 ID는 SAP HANA 호스트와 스토리지 컨트롤러에서 동일해야 합니다. 스토리지 클러스터에서 다음 명령을 입력하여 그룹과 사용자를 생성합니다.

....
vserver services unix-group create -vserver <vserver> -name <group name> -id <group id>
vserver services unix-user create -vserver <vserver> -user <user name> -id <user-id> -primary-gid <group id>
....
또한 SVM의 UNIX 사용자 루트의 그룹 ID를 0으로 설정합니다.

....
vserver services unix-user modify -vserver <vserver> -user root -primary-gid 0
....