---
sidebar: sidebar 
permalink: lifecycle/libelle-sc-overview.html 
keywords: tr4929, 4929, overview, introduction 
summary: SAP 라이프사이클 관리를 최적화하기 위한 NetApp 솔루션은 SAP AnyDB 및 SAP HANA 데이터베이스에 통합되어 있습니다. 또한, NetApp은 SAP 라이프사이클 관리 툴에 통합되어 효율적인 애플리케이션 통합 데이터 보호와 유연한 SAP 테스트 시스템 프로비저닝을 결합합니다. 
---
= TR-4929: Libelle SystemCopy를 사용하여 SAP 시스템 복사 작업 자동화
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Holger Zecha, Tobias Brandl, NetApp Franz Die그루버, Libelle

오늘날의 역동적인 비즈니스 환경에서 기업은 지속적인 혁신을 제공하고 변화하는 시장에 신속하게 대응해야 합니다. 이러한 경쟁 상황에서 업무 프로세스에서 더 큰 유연성을 구현하는 기업은 시장 요구에 보다 효율적으로 적응할 수 있습니다.

변화하는 시장 요구도 정기적인 통합, 변경 및 업데이트가 필요한 회사의 SAP 환경에 영향을 미칩니다. IT 부서는 더 적은 리소스로 더 짧은 기간에 걸쳐 이러한 변경 사항을 구현해야 합니다. 이러한 변경 사항을 배포할 때 위험을 최소화하려면 프로덕션 환경에서 실제 데이터를 포함하는 추가 SAP 시스템이 필요한 철저한 테스트와 교육이 필요합니다.

이러한 시스템을 프로비저닝하기 위한 기존의 SAP 수명 주기 관리 방식은 주로 수동 프로세스를 기반으로 합니다. 이러한 수동 프로세스는 오류가 발생하기 쉽고 시간이 많이 소모되므로 혁신이 지연되고 비즈니스 요구사항에 대한 응답이 지연됩니다.

SAP 라이프사이클 관리를 최적화하기 위한 NetApp 솔루션은 SAP AnyDB 및 SAP HANA 데이터베이스에 통합되어 있습니다. 또한, NetApp은 SAP 라이프사이클 관리 툴에 통합되어 효율적인 애플리케이션 통합 데이터 보호와 유연한 SAP 테스트 시스템 프로비저닝을 결합합니다.

NetApp 솔루션은 최대 규모의 데이터베이스도 포함하여 엄청난 양의 데이터를 효율적으로 관리하는 문제를 해결하지만, 전체 종단간 SAP 시스템 복사 및 새로 고침 작업에는 소스 SAP 시스템의 ID를 타겟 시스템으로 완전히 변경하기 위한 사전 및 사후 복제 작업이 포함되어야 합니다. SAP는 에 포함된 필수 작업에 대해 설명합니다 https://help.sap.com/viewer/6ffd9a3438944dc39dfe288d758a2ed5/LATEST/en-US/f6abb90a62aa4695bb96871a89287704.html["동종 SAP 시스템 복제 가이드"^]. NetApp의 파트너는 수동 프로세스 수를 줄이고 SAP 시스템 복사 프로세스의 품질과 안정성을 개선하기 위해 https://www.libelle.com["리벨"^] 을(를) 개발했습니다 https://www.libelle.com/products/systemcopy["Llibelle SystemCopy(LSC)"^] 도구. Libelle은 SAP 시스템 사본용 NetApp 솔루션을 LSC에 통합하여 제공합니다 https://www.youtube.com/watch?v=wAFyA_WbNm4["기록적인 시간 내에 완벽한 엔드 투 엔드 자동화 시스템 복사본 제공"^].



== 애플리케이션 통합 스냅샷 복사본 작업

스토리지 계층에서 애플리케이션 정합성이 보장된 NetApp 스냅샷 복사본을 생성하는 기능은 이 문서에 설명된 시스템 복사본 및 시스템 클론 복제 작업의 기반입니다. 스토리지 기반 스냅샷 복사본은 SAP HANA용 NetApp SnapCenter 플러그인 또는 네이티브 NetApp ONTAP 시스템의 DB나 을 사용하여 생성됩니다 https://docs.microsoft.com/en-us/azure/azure-netapp-files/azacsnap-introduction["Microsoft Azure Application Consistent Snapshot 툴"^] Microsoft Azure에서 실행되는 SAP HANA 및 Oracle 데이터베이스에서 제공하는 인터페이스 SAP HANA를 사용하는 경우 SnapCenter 및 AzAcSnap은 SAP HANA 백업 카탈로그에 Snapshot 복사본을 등록하여 복원 및 복구뿐만 아니라 클론 복제 작업에 백업을 사용할 수 있습니다.



== 오프 사이트 백업 및/또는 재해 복구 데이터 복제

애플리케이션 정합성이 보장된 Snapshot 복사본을 스토리지 계층에서 외부 백업 사이트로 복제하거나 SnapCenter가 사내에서 제어하는 재해 복구 사이트로 복제할 수 있습니다. 복제는 블록 변경을 기반으로 하므로 공간 및 대역폭 효율성이 뛰어납니다. Azure NetApp Files가 설치된 Azure에서 실행되는 SAP HANA 및 Oracle 시스템에 대해 CRR(Cross Region Replication) 기능을 사용하여 Azure 지역 간에 Azure NetApp Files 볼륨을 효율적으로 복제하는 동일한 기술을 사용할 수 있습니다.



== SAP 시스템 복제 또는 클론 작업에 스냅샷 복사본을 사용합니다

NetApp 기술 및 소프트웨어 통합을 통해 SAP 시스템 복사 또는 클론 복제 작업에 소스 시스템의 Snapshot 복사본을 사용할 수 있습니다. 이 스냅샷 복제본은 SAP 운영 시스템에 사용되는 동일한 스토리지, 외부 백업에 사용되는 스토리지(예: Azure의 Azure NetApp Files 백업) 또는 재해 복구 사이트의 스토리지(Azure NetApp Files CRR 타겟 볼륨)에서 선택할 수 있습니다. 이러한 유연성 덕분에 필요한 경우 개발 및 테스트 시스템을 운영 시스템과 분리할 수 있으며 재해 복구 사이트에서 재해 복구 테스트 등의 다른 시나리오를 다룰 수 있습니다.



== 자동화를 제공합니다

SAP 테스트 시스템 프로비저닝에 대한 다양한 시나리오 및 사용 사례가 있으며 자동화 수준에 대한 요구사항이 있을 수도 있습니다. SAP용 NetApp 소프트웨어 제품은 SAP 및 기타 타사 공급업체(예: Libelle)의 데이터베이스 및 라이프사이클 관리 제품에 통합되어 다양한 시나리오 및 자동화 수준을 지원합니다.

SAP HANA 및 SAP AnyDB용 플러그인을 갖춘 NetApp SnapCenter 또는 Azure의 AzAcSnap은 애플리케이션 정합성이 보장된 Snapshot 복사본을 기반으로 필요한 스토리지 볼륨 클론을 프로비저닝하고 시작된 SAP 데이터베이스까지 필요한 모든 호스트 및 데이터베이스 작업을 실행하는 데 사용됩니다. 사용 사례에 따라 SAP 시스템 복사, 시스템 클론, 시스템 새로 고침 또는 SAP 사후 처리 같은 추가 수동 단계가 필요할 수 있습니다. 자세한 내용은 다음 섹션에서 다룹니다.

LSC(Libelle SystemCopy) 자동화를 사용하면 SAP 테스트 시스템의 완전 자동화된 엔드 투 엔드 프로비저닝 또는 업데이트를 수행할 수 있습니다. SnapCenter 또는 AzAcSnap을 LSC에 통합하는 방법은 이 문서에서 자세히 설명합니다.



== Libelle SystemCopy를 참조하십시오

Libelle SystemCopy는 완전히 자동화된 시스템 및 가로 복사본을 생성하는 프레임워크 기반 소프트웨어 솔루션입니다. 버튼 하나로 QA 및 테스트 시스템을 새로운 생산 데이터로 업데이트할 수 있습니다. Libelle SystemCopy는 기존의 모든 데이터베이스와 운영 체제를 지원하며 모든 플랫폼에 고유한 복사 메커니즘을 제공하지만 동시에 NetApp Snapshot 복사본 및 NetApp FlexClone 볼륨과 같은 백업/복원 절차나 스토리지 도구를 통합합니다. 시스템 복사 중에 필요한 작업은 SAP ABAP 스택 외부에서 제어됩니다. 이러한 방식으로 SAP 애플리케이션의 전송 또는 기타 변경이 필요하지 않습니다. 일반적으로 시스템 복사 절차를 성공적으로 완료하는 데 필요한 모든 단계는 다음 네 단계로 분류할 수 있습니다.

* * Check phase. * 관련 시스템 환경을 확인한다.
* * Pre phase. * 시스템 복사를 위해 대상 시스템을 준비합니다.
* * 복사 단계. * 소스에서 타겟 시스템으로 실제 운영 데이터베이스의 복사본을 제공합니다.
* * Post phase. * 복사 후 모든 작업을 수행하여 동종 시스템 복사 절차를 완료하고 업데이트된 대상 시스템을 제공합니다.


복사 단계에서는 NetApp Snapshot 및 FlexClone 기능을 사용하여 최대 규모의 데이터베이스에서도 몇 분 안에 필요한 시간을 최소화할 수 있습니다.

Check, Pre 및 Post 단계의 경우, LSC는 일반적인 새로 고침 작업의 95%를 포괄하는 450개 이상의 사전 구성된 작업을 제공합니다. 그 결과, LSC는 SAP 표준에 따라 자동화를 수용한다. LSC의 소프트웨어 정의 특성 때문에 고객 SAP 환경의 특정 요구 사항을 충족하도록 시스템 업데이트 프로세스를 쉽게 조정하고 향상시킬 수 있습니다.



== SAP 시스템 업데이트 및 클론 복제 사용 사례

소스 시스템의 데이터를 타겟 시스템에서 사용할 수 있도록 여러 가지 시나리오가 있습니다.

* 품질 보증 및 테스트 및 교육 시스템의 정기적인 업데이트
* 논리적 손상을 해결하기 위한 고장 수리 또는 수리 시스템 환경 생성
* 재해 복구 테스트 시나리오


복구 시스템과 재해 복구 테스트 시스템은 일반적으로 업데이트된 테스트 및 교육 시스템에 대해 SAP 시스템 클론(광범위한 사후 처리 작업이 필요하지 않음)을 사용하여 제공되지만 소스 시스템과 공존할 수 있도록 이러한 사후 처리 단계를 적용해야 합니다. 따라서 이 문서에서는 SAP 시스템 업데이트 시나리오에 대해 중점적으로 설명합니다. 다양한 사용 사례에 대한 자세한 내용은 기술 보고서를 참조하십시오 https://docs.netapp.com/us-en/netapp-solutions-sap/lifecycle/sc-copy-clone-introduction.html["TR-4667: SnapCenter를 사용하여 SAP HANA 시스템 복제 및 클론 작업 자동화"^].

이 문서의 나머지 부분은 두 부분으로 나뉩니다. 첫 번째 부분에서는 NetApp SnapCenter를 Libelle SystemCopy for SAP HANA 및 온프레미스 NetApp ONTAP 시스템에서 실행되는 SAP AnyDB 시스템에 통합하는 방법을 설명합니다. 두 번째 부분에서는 제공된 Azure NetApp Files를 사용하여 Microsoft Azure에서 실행되는 SAP HANA 시스템용 AzAcSnap과 LSC의 통합에 대해 설명합니다. 언더레이 ONTAP 기술은 동일하지만 Azure NetApp Files는 기본 ONTAP 설치와 비교하여 다양한 인터페이스 및 툴 통합(예: AzAcSnap)을 제공합니다.

link:libelle-sc-sap-hana-system-refresh-with-lsc-and-snapcenter.html["다음: LSC 및 SnapCenter를 통해 SAP HANA 시스템 업데이트"]
